
[client]
	#Allowed Values: KEYSYM, SCANCODE, MOUSE
	keyTypeOptionsMenu = "KEYSYM"
	#Allowed Values: KEYSYM, SCANCODE, MOUSE
	keyTypeSprintHold = "KEYSYM"
	#Allowed Values: CONTROL, SHIFT, ALT, NONE
	keyModOptionsMenu = "NONE"
	#Range: 0 ~ 7
	flySpeedBoost = 3
	#Range: > -2147483648
	keyCodeSneakToggle = 92
	#Range: > -2147483648
	keyCodeSprintToggle = 92
	#Allowed Values: CONTROL, SHIFT, ALT, NONE
	keyModSprintHold = "NONE"
	#Range: > -2147483648
	keyCodeSprintHold = 340
	enableAllDirs = false
	#Range: > -2147483648
	keyCodeOptionsMenu = 92
	enableDoubleTap = false
	#Allowed Values: CONTROL, SHIFT, ALT, NONE
	keyModSneakToggle = "NONE"
	#Allowed Values: KEYSYM, SCANCODE, MOUSE
	keyTypeSprintToggle = "KEYSYM"
	flyOnGround = false
	disableMod = false
	#Allowed Values: TAP, HOLD
	sprintKeyMode = "TAP"
	#Allowed Values: CONTROL, SHIFT, ALT, NONE
	keyModSprintToggle = "NONE"
	#Allowed Values: KEYSYM, SCANCODE, MOUSE
	keyTypeSneakToggle = "KEYSYM"

